[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
match_3 = "45jqMGFZJ7FqiKxNgnsJvYjznhspjZBXxV3sotnkhUT3"

[programs.localnet]
match_3 = "45jqMGFZJ7FqiKxNgnsJvYjznhspjZBXxV3sotnkhUT3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/star/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
