[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
match_3 = "Bo62M4w6RYsffaCxKSNa1GnZX1waKJcBsrrPm68HXvae"

[programs.localnet]
match_3 = "Bo62M4w6RYsffaCxKSNa1GnZX1waKJcBsrrPm68HXvae"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/star/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
